### ISSUE TITLE
Modded Interiors

### ISSUE THREAD

**Issue by VioletXe** [AudioKnight/Starlancer#17]
This is probably a known issue, maybe, but thought I'd leave this here. Sandworms seem to not function properly when placed in modded interiors. Since I imagine Starlancer was only made for Facility interiors in mind, are there any plans to make Sandworms work on other interiors, or would that be on the interior developer to make?
![20240227114811_1](https://github.com/AudioKnight/Starlancer/assets/157070685/f4b3def4-3d7d-40b8-be45-e5475ce16e8a)

**Comment by AudioKnight** [comment]
Sorry, haven't checked Github in a few. It really boils down to how the interior tileset is made. If it follows vanilla tag/layer convention, it should work normally, but otherwise I wouldn't have a clue. The only code I actually touch regarding interior sandworms is to make them reset at a random inside node after they attack, otherwise they warp to the surface and break.
