### ISSUE TITLE
request

### ISSUE THREAD

**Issue by Kingtonberry** [AudioKnight/Starlancer#18]
I have FairGiants, which seems to be working fine with your aiFix for the most part, but also Forest Giant Motionsense, which seems to stop working when I couple all 3. It worked before with FairGiants before adding aiFix. Staying still they now still see me. Is it possible to have all 3 working together?
I'm loving the mods anyways, they've enabled so many possibilities for moons and the moons already using it are great. I appreciate it. Thank you!

**Comment by AudioKnight** [comment]
I'll look into it! Thank you for the kind words ^^

**Comment by AudioKnight** [comment]
@Kingtonberry so I looked into it a bit and my mod and FoGiMoSe don't touch any of the same code, and since they're already outside enemies (unless you're spawning them inside), they shouldn't really be affected by my AIFix in the first place

It seems like Motionsense uses transpilers to patch their code into LC, which is currently beyond me, so if you haven't already, I'd ask them to look into it as well. If they happen to know of a fix that should be done on my end, they're free to reach out to me on the discord :)

**Comment by Kingtonberry** [comment]
Thanks so much for checking it out!
One more thing to note is that Puffers seem only aggressive outdoors on Solace and Bozoros, and I don't think it's your aiFix mod, but I wish i could contact the Bozoros moon creator LethalMatt, but they aren't on github. On that moon, the Puffers still get stuck ramming each other in place until you approach them, then they chase you until you deaggro them, and they then run to another location and ram each other again. The other outdoor enemies seem to act appropriately there though.
Anyways thanks for your time!

**Comment by AudioKnight** [comment]
Are you using Diversity? One of the latest updates added a revamp to the spore lizards
