### ISSUE TITLE
Spam while playing

### ISSUE THREAD

**Issue by VanilaBOI** [AudioKnight/Starlancer#9]
Everytime I'm on the Moon, I get this line spammed and have the feeling it's why the game lags for all of us.

[Error  : Unity Log] "CalculatePolygonPath" can only be called on an active agent that has been placed on a NavMesh.
[Error  : Unity Log] "CalculatePolygonPath" can only be called on an active agent that has been placed on a NavMesh.
[Error  : Unity Log] "CalculatePolygonPath" can only be called on an active agent that has been placed on a NavMesh.
[Error  : Unity Log] "CalculatePolygonPath" can only be called on an active agent that has been placed on a NavMesh.
[Error  : Unity Log] "CalculatePolygonPath" can only be called on an active agent that has been placed on a NavMesh.

**Comment by AudioKnight** [comment]
This was another error I wasn't able to replicate, but I saw from your other post that you have a mod called Symbiosis that affects "the dynamics of lethal company by increasing interactions and dynamics among monsters, items, and players."

I'm fairly certain the issue was not caused by StarlancerMoons. Is it happening on vanilla moons, all custom moons, or mine in particular?

**Comment by VanilaBOI** [comment]
I have only noticed it on this moon because it appeared so much.
Probably only really triggers if played with other people

**Comment by AudioKnight** [comment]
It's possible that it's more noticeable because of the higher power cap on Auralis. If you could possibly test it in a clean profile with other players to see if it still appears, it would be much appreciated.

**Comment by AudioKnight** [comment]
Also, were you in a custom dungeon when the error was thrown? Because it's possible there's an issue with their navmesh if so.

**Comment by VanilaBOI** [comment]
Maybe it was sco foundation now that I think about it
